# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('update_dt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelbuddy_app.Trip'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelbuddy_app.User'),
        ),
    ]
