# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy_app', '0002_auto_20161118_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='description',
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
